services:
  db:
    image: postgres:16
    container_name: question-service-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: question_service
    volumes:
      - db-data:/var/lib/postgresql/data
  api:
    build: .
    container_name: question-service-api
    depends_on:
      - db
    environment:
      HTTP_PORT: ":8080"
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: question_service
      DB_SSLMODE: disable
    ports:
      - "8080:8080"

volumes:
  db-data:
