version: "3.9"

services:
  question-service-postgres:
    image: postgres:16
    container_name: question-service-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: question_service
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  question-service-migrate:
      build: .
      container_name: question-service-migrate
      command: [ "/app/migrate" ]
      environment:
        HTTP_PORT: ":8080"
        DB_HOST: question-service-postgres
        DB_PORT: "5432"
        DB_USER: postgres
        DB_PASS: postgres
        DB_NAME: question_service
        DB_SSLMODE: disable
      depends_on:
        - question-service-postgres

  question-service-api:
    build: .
    container_name: question-service-api
    command: ["/app/api"]
    environment:
      HTTP_PORT: ":8080"
      DB_HOST: question-service-postgres
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: question_service
      DB_SSLMODE: disable
    ports:
      - "8081:8080"
    depends_on:
      - question-service-migrate

volumes:
  postgres_data:
